source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'client' do
    pod 'Alamofire', '~> 4.0'
    pod 'CocoaLumberjack/Swift'
    pod 'UIColor_Hex_Swift'
end
